### ISSUE TITLE
Adding: Blogger/Digg/Delicious/Tumblr/Linkedin/Email and Google Bug Fix

### ISSUE THREAD

**Issue by ryan0cole** [tabalinas/jssocials#104]
Is it possible to provide package update to include important buttons below and fix Google bug?
1.Blogger
2.Digg
3.Delicious
4.Tumblr
5.Linkedin
6.Email

The help docs do not specify where to find urls of services shares and counts: How to add a new custom share is described in the docs http://js-socials.com/docs/#custom-share

**Comment by tabalinas** [comment]
Linkedin and Email shares already supported. As for the rest, feel free to do a PR. 
Docs cannot specify where to find share and count urls, because it depends on social network. So just try to find it in the internet or in the social network docs.
For Google bug yes, I will release a patch version soon.
