### ISSUE TITLE
The social name on Mouse Over

### ISSUE THREAD

**Issue by MarcoProf** [tabalinas/jssocials#115]
Add new oprion: showTitle: true
New option to get the social name on Mouse Over.

**Comment by tabalinas** [comment]
Use [on](http://js-socials.com/docs/#on-object) option to attach event handlers to show/hide a tooltip if necessary.

As for build-in option, currently I'm not sure if it's always needed. 
Showing just share name would be weird (at least because it's in lowercase). This means that probably a separate option for a tooltip value is needed. For this let's wait for more requests.
