### ISSUE TITLE
Where is file font-awesome.css?

### ISSUE THREAD

**Issue by jfoclpf** [tabalinas/jssocials#139]
In [documentation](http://js-socials.com/start-using/) you refer to link to file `font-awesome.css`

Where is that file?

I mean, I did exactly as you stated in documentation, and that's what I get:

![capturar](https://cloud.githubusercontent.com/assets/3984909/24778732/8128ac4c-1b2c-11e7-9406-282b0397e995.JPG)

thank you

**Comment by jfoclpf** [comment]
Thanks to the [file shared](https://github.com/tabalinas/jssocials/issues/116#issuecomment-257509472) by @mspanish I go it :) 

You should add such file in the repository

**Comment by tabalinas** [comment]
I cannot add font-awesome to the repo since this is an external project, and in fact js-socials can work perfectly with any other icon library. It's only defaults that are bound to font-awesome (as a most widely used lib).
I guess the solution would be to more precisely explain that font-awesome should be downloaded separately and probably provide a link to it.
What you think?

**Comment by jfoclpf** [comment]
I think it is a perfect idea. But it would also be preferable to add to the repository by default, the files provided by @mspanish. Her [files set](https://github.com/tabalinas/jssocials/files/563596/fonts.zip) seem to be lighter than the [font-awesome.min.css](http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css)

**Comment by tabalinas** [comment]
Yes, this file set is great, we really appreciate @mspanish efforts. 
The thing is including it in the repo directly would not be ideal, since component is not hardly dependent on any of these iconsets. So I do believe it should be described better on the website of the project.

@jfoclpf, thank you for the feedback, it will be considered.
