### ISSUE TITLE
Privacy Settings?! (shariff)

### ISSUE THREAD

**Issue by iocron** [tabalinas/jssocials#142]
Are there any privacy settings possible? Like https://github.com/heiseonline/shariff ?

Currently all the data is already beeing sent to the social media platforms when i load the site, but in the EU and some other regions its more safe to not send this data to those platforms, instead it should be only send if i click on one of the social media share icons (like in the social media shariff plugin).

**Comment by Ruud68** [comment]
The 'sending' of data is done when fetching the counters for the different platforms. When you disable the counters then there is no data sent. Because jssocials script is run locally in the browser of the client, when fetching e.g. the share stats from facebook: facebook knows your clients ip because it is his/her browser that fetches the stats.

Only work-around I see for having counters that do not sent the user data is to have e.g. a php server side script that fetches the counters from the social media platforms. Doing it that way it is your servers data that is shared with e.g. facebook. This will put extra load on your server so you probably end up with caching of stats etc.

**Comment by tabalinas** [comment]
@Ruud68, thanks for the exhaustive answer!
