### ISSUE TITLE
shared count of twitter and google plus is not working 

### ISSUE THREAD

**Issue by adrianmak** [tabalinas/jssocials#149]
I shared a post to google plus and twitter, but the shared count did show on.
Shared count only work for facebook

**Comment by Ruud68** [comment]
Twitter stopped providing share counts. So there is no count anymore for twitter unless you doe the counting yourself (or from a third-party provider).
https://blog.twitter.com/developer/en_us/a/2015/hard-decisions-for-a-sustainable-platform.html

GooglePlus share count is broken for some time now, this is due to a change on the Google side.
https://github.com/tabalinas/jssocials/issues/92

Linkedin, stumbleupon, facevook etc. still do work correct.
