### ISSUE TITLE
Updating a pinterest "media" option doesn't refresh the links

### ISSUE THREAD

**Issue by nicolasbinet** [tabalinas/jssocials#31]
Following issue #25 not all options are updated.

"_passOptionToShares" limits the options to Url & Text, whereas it should be unlimited to allow for custom social networks options.

**Comment by tabalinas** [comment]
You are right. But the problem is we cannot pass all options to shares from jssocials. Only url and text are common. All custom options related only to particular share. 
In the next upcoming minor release, new method `shareOption` is going to be introduced, to be able to get and set options of the shares.
