### ISSUE TITLE
Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by Angristan** [tabalinas/jssocials#39]
I get this about that : 
``` 
<script>
        $("#share").jsSocials({
            shares: ["email", "twitter", "facebook", "googleplus", "linkedin", "pinterest", "whatsapp"]
        });
    </script>
```

**Comment by tabalinas** [comment]
Are you sure you've added jQuery to the page?
See how to start using jsSocials on the project site http://js-socials.com/start-using/

**Comment by Angristan** [comment]
Yes jQuery is already present on my website.
I incuded the js and the two CSS files + the script but it get this error

**Comment by tabalinas** [comment]
I guess then you include jQuery after this script. You need to put link to jQuery before.

**Comment by Angristan** [comment]
Yep you're right but all my JS is deffered at the end, and everything is working fine

**Comment by tabalinas** [comment]
yes, then you need to defer the creation of js-socials too, to have it executed when jQuery is available. That's the issue, there is nothing to do with jsSocials.

**Comment by Angristan** [comment]
But, when the page is loaded, jQuery is loaded too so what's the problem ?

**Comment by Ruud68** [comment]
The problem is in the order of loading. You can check that in the source of your web page.
If jssocials.min.js comes before jquery.min.js then there is this issue.

Had the same issue on some sites with my Joomla plugin. Solved it to make loading of jssocials.min.js dependend on jquery being loaded.

**Comment by Angristan** [comment]
So where is the problem now ? https://lut.im/QH5ZIdl1DX/leJzr1xXJKlYxEnF.png

**Comment by Ruud68** [comment]
do you have url so I can have a look?

**Comment by Angristan** [comment]
Nope, I use autoptimize on WordPress and I can't keep all the css and JS like that forever, nevermind

**Comment by navalee** [comment]
I know this thread is old and closed but I just ran into this issue. It was working fine on my non wordpress pages but not my wordpress pages. The top answer here resolved it for me:
http://stackoverflow.com/questions/7975093/typeerror-undefined-is-not-a-function-evaluating-document

basically replacing $ with jquery in the jssocials.js file... so the two (window, $... become (window, jQuery...

hopefully this can help others if they run into this problem as well.

**Comment by tabalinas** [comment]
@navalee, thanks for the comment.
Missed continuing conversation with @Angristan, but I guess that problem is not in the order of js-socials and jquery scripts, the problem of this `<script> /* js-socials creation */ </script>` block that creates the control. Meaning when it's executed there is no jQuery, so this block goes before the link to jQuery.
